version: '3.8'

services:
  webapi:
    container_name: flowcycle-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Base=Host=db;Port=5432;Database=mywebapi;Username=postgres;Password=mysecretpassword
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - backend-network
  
  db:
    container_name: flowcycle-db
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=mywebapi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mywebapi"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  postgres_data: